export type Role = "manager" | "staff";

export interface Category {
  id: string;
  name: string;
  slug: string;
}

export interface Variant {
  id: string;
  sku: string;
  name: string;
  size: string;
  color: string;
  colorCode: string;
  sellingPrice: number;
  costPrice: number;
  barcode?: string;
}

export interface Product {
  id: string;
  sku: string;
  name: string;
  description: string;
  categoryId: string;
  images: string[];
  tags: string[];
  active: boolean;
  stock: number;
  variants: Variant[];
  fabric: string;
  care: string;
  season?: string;
  brand?: string;
  compareAt?: number;
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  totalPurchases: number;
  visitCount: number;
  email?: string;
  address?: string;
  birthday?: string;
  notes?: string;
  tags?: string[];
}

export type PaymentMethod = "qris" | "cash" | "transfer" | "shopee";
export type TransactionStatus = "pending" | "paid" | "cancelled" | "refunded";

export interface TransactionItem {
  productId: string;
  variantId: string;
  name: string;
  sku: string;
  size: string;
  color: string;
  quantity: number;
  unitPrice: number;
  costPrice: number;
  discount: number;
  total: number;
}

export interface Transaction {
  id: string;
  number: string;
  cashier: string;
  customerId?: string;
  customerName?: string;
  status: TransactionStatus;
  paymentMethod: PaymentMethod;
  paymentStatus: "pending" | "paid" | "failed" | "expired";
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  amountPaid: number;
  change: number;
  items: TransactionItem[];
  createdAt: string;
  qrisRef?: string;
  photoProof?: string;
}

export interface Shift {
  id: string;
  staff_name: string;
  opened_at: string;
  closed_at?: string;
  startingCash: number;
  endingCash?: number;
  totalTransactions: number;
  totalSales: number;
  totalQris: number;
  totalCash: number;
  status: "open" | "closed" | "reconciled";
}

export const BASE_URL =
  typeof window !== "undefined"
    ? window.location.origin
    : "https://kebaya-oma.id";

export const categories: Category[] = [
  { id: "cat-kebaya", name: "Kebaya", slug: "kebaya" },
  { id: "cat-batik", name: "Kain Batik", slug: "batik" },
  { id: "cat-accessories", name: "Aksesoris", slug: "accessories" },
];

function img(emoji: string): string {
  return `https://placehold.co/400x500/831843/ffffff?text=${encodeURIComponent(emoji)}`;
}

export const products: Product[] = [
  {
    id: "p1",
    sku: "ANTING",
    name: "Anting",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v1",
        sku: "ANTING-ANTING",
        name: "Anting",
        size: "One Size",
        color: "Anting",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
      {
        id: "v2",
        sku: "ANTING-ANTING-S",
        name: "Anting S",
        size: "One Size",
        color: "Anting S",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 25000,
        barcode: "",
      },
      {
        id: "v3",
        sku: "ANTING-ANTING-M",
        name: "Anting M",
        size: "One Size",
        color: "Anting M",
        colorCode: "#000000",
        sellingPrice: 75000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v4",
        sku: "ANTING-ANTING-L",
        name: "anting l",
        size: "One Size",
        color: "anting l",
        colorCode: "#000000",
        sellingPrice: 100000,
        costPrice: 50000,
        barcode: "",
      },
    ],
  },
  {
    id: "p2",
    sku: "BAGCHRAM",
    name: "Bagchram",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v5",
        sku: "BAGCHRAM-BAGCHRAM",
        name: "bagchram",
        size: "One Size",
        color: "bagchram",
        colorCode: "#000000",
        sellingPrice: 25000,
        costPrice: 10000,
        barcode: "",
      },
    ],
  },
  {
    id: "p3",
    sku: "BANDANA",
    name: "Bandana",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v6",
        sku: "BANDANA-BANDANA",
        name: "Bandana",
        size: "One Size",
        color: "Bandana",
        colorCode: "#000000",
        sellingPrice: 20000,
        costPrice: 10000,
        barcode: "",
      },
    ],
  },
  {
    id: "p4",
    sku: "BATIK",
    name: "Batik",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v7",
        sku: "BATIK-TOP-BATIK",
        name: "Top Batik",
        size: "One Size",
        color: "Top Batik",
        colorCode: "#000000",
        sellingPrice: 120000,
        costPrice: 60000,
        barcode: "",
      },
      {
        id: "v8",
        sku: "BATIK-TOP-BATIK-P",
        name: "Top Batik P",
        size: "One Size",
        color: "Top Batik P",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 100000,
        barcode: "",
      },
      {
        id: "v9",
        sku: "BATIK-BATIK-EKA",
        name: "Batik eka",
        size: "One Size",
        color: "Batik eka",
        colorCode: "#000000",
        sellingPrice: 140000,
        costPrice: 87500,
        barcode: "",
      },
      {
        id: "v10",
        sku: "BATIK-BATIK-TOP",
        name: "Batik Top",
        size: "One Size",
        color: "Batik Top",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 87500,
        barcode: "",
      },
      {
        id: "v11",
        sku: "BATIK-BATIK-S",
        name: "batik s",
        size: "One Size",
        color: "batik s",
        colorCode: "#000000",
        sellingPrice: 138500,
        costPrice: 87500,
        barcode: "",
      },
      {
        id: "v12",
        sku: "BATIK-BATIK-CAP",
        name: "batik cap",
        size: "One Size",
        color: "batik cap",
        colorCode: "#000000",
        sellingPrice: 750000,
        costPrice: 375000,
        barcode: "",
      },
      {
        id: "v13",
        sku: "BATIK-BATIK",
        name: "batik",
        size: "One Size",
        color: "batik",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 100000,
        barcode: "",
      },
      {
        id: "v14",
        sku: "BATIK-BLUS-BATIK",
        name: "blus batik",
        size: "One Size",
        color: "blus batik",
        colorCode: "#000000",
        sellingPrice: 140000,
        costPrice: 70000,
        barcode: "",
      },
      {
        id: "v15",
        sku: "BATIK-BATIK-OVERSIZE",
        name: "batik oversize",
        size: "One Size",
        color: "batik oversize",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 100000,
        barcode: "",
      },
      {
        id: "v16",
        sku: "BATIK-BATIK-TULIS",
        name: "batik tulis",
        size: "One Size",
        color: "batik tulis",
        colorCode: "#000000",
        sellingPrice: 550000,
        costPrice: 250000,
        barcode: "",
      },
    ],
  },
  {
    id: "p5",
    sku: "BC",
    name: "Bc",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v17",
        sku: "BC-BC",
        name: "BC",
        size: "One Size",
        color: "BC",
        colorCode: "#000000",
        sellingPrice: 20000,
        costPrice: 8100,
        barcode: "",
      },
    ],
  },
  {
    id: "p6",
    sku: "BROS",
    name: "Bros",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v18",
        sku: "BROS-BROS",
        name: "bros",
        size: "One Size",
        color: "bros",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 8000,
        barcode: "",
      },
    ],
  },
  {
    id: "p7",
    sku: "BUSTIER",
    name: "Bustier",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v19",
        sku: "BUSTIER-BUSTIER",
        name: "Bustier",
        size: "One Size",
        color: "Bustier",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 70000,
        barcode: "",
      },
    ],
  },
  {
    id: "p8",
    sku: "CINCIN",
    name: "Cincin",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v20",
        sku: "CINCIN-CINCIN-PERAK-S",
        name: "Cincin Perak S",
        size: "One Size",
        color: "Cincin Perak S",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 20000,
        barcode: "",
      },
      {
        id: "v21",
        sku: "CINCIN-CINCIN-PERAK-M",
        name: "Cincin Perak M",
        size: "One Size",
        color: "Cincin Perak M",
        colorCode: "#000000",
        sellingPrice: 75000,
        costPrice: 40000,
        barcode: "",
      },
      {
        id: "v22",
        sku: "CINCIN-CINCIN-PERAK-L",
        name: "Cincin Perak L",
        size: "One Size",
        color: "Cincin Perak L",
        colorCode: "#000000",
        sellingPrice: 100000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v23",
        sku: "CINCIN-CINCIN",
        name: "cincin",
        size: "One Size",
        color: "cincin",
        colorCode: "#000000",
        sellingPrice: 15000,
        costPrice: 5000,
        barcode: "",
      },
      {
        id: "v24",
        sku: "CINCIN-CINCIN-2",
        name: "cincin 2",
        size: "One Size",
        color: "cincin 2",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 20000,
        barcode: "",
      },
      {
        id: "v25",
        sku: "CINCIN-CINCIN-S",
        name: "cincin s",
        size: "One Size",
        color: "cincin s",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 10000,
        barcode: "",
      },
      {
        id: "v26",
        sku: "CINCIN-CINCIN-COWOK",
        name: "cincin cowok",
        size: "One Size",
        color: "cincin cowok",
        colorCode: "#000000",
        sellingPrice: 35000,
        costPrice: 15000,
        barcode: "",
      },
    ],
  },
  {
    id: "p9",
    sku: "CURATED",
    name: "Curated",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v27",
        sku: "CURATED-CURATED",
        name: "Curated",
        size: "One Size",
        color: "Curated",
        colorCode: "#000000",
        sellingPrice: 80000,
        costPrice: 40000,
        barcode: "",
      },
      {
        id: "v28",
        sku: "CURATED-CURATED-MAN",
        name: "curated man",
        size: "One Size",
        color: "curated man",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 100000,
        barcode: "",
      },
    ],
  },
  {
    id: "p10",
    sku: "DASTER",
    name: "Daster",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v29",
        sku: "DASTER-DASTER",
        name: "Daster",
        size: "One Size",
        color: "Daster",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 37500,
        barcode: "",
      },
      {
        id: "v30",
        sku: "DASTER-DASTER-BATIK",
        name: "daster batik",
        size: "One Size",
        color: "daster batik",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
    ],
  },
  {
    id: "p11",
    sku: "DOMPET",
    name: "Dompet",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v31",
        sku: "DOMPET-DOMPET",
        name: "dompet",
        size: "One Size",
        color: "dompet",
        colorCode: "#000000",
        sellingPrice: 15000,
        costPrice: 6000,
        barcode: "",
      },
    ],
  },
  {
    id: "p12",
    sku: "DRES",
    name: "Dres",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v32",
        sku: "DRES-DRES",
        name: "dres",
        size: "One Size",
        color: "dres",
        colorCode: "#000000",
        sellingPrice: 350000,
        costPrice: 150000,
        barcode: "",
      },
    ],
  },
  {
    id: "p13",
    sku: "GANCI",
    name: "Ganci",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v33",
        sku: "GANCI-GANCI",
        name: "ganci",
        size: "One Size",
        color: "ganci",
        colorCode: "#000000",
        sellingPrice: 10000,
        costPrice: 5000,
        barcode: "",
      },
    ],
  },
  {
    id: "p14",
    sku: "GELANG",
    name: "Gelang",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v34",
        sku: "GELANG-GELANG",
        name: "Gelang",
        size: "One Size",
        color: "Gelang",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
      {
        id: "v35",
        sku: "GELANG-GELANG-E",
        name: "Gelang E",
        size: "One Size",
        color: "Gelang E",
        colorCode: "#000000",
        sellingPrice: 15000,
        costPrice: 10000,
        barcode: "",
      },
      {
        id: "v36",
        sku: "GELANG-GELANG-BATU",
        name: "gelang batu",
        size: "One Size",
        color: "gelang batu",
        colorCode: "#000000",
        sellingPrice: 100000,
        costPrice: 50000,
        barcode: "",
      },
    ],
  },
  {
    id: "p15",
    sku: "GIWANG",
    name: "Giwang",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v37",
        sku: "GIWANG-GIWANG",
        name: "giwang",
        size: "One Size",
        color: "giwang",
        colorCode: "#000000",
        sellingPrice: 30000,
        costPrice: 15000,
        barcode: "",
      },
    ],
  },
  {
    id: "p16",
    sku: "JAM",
    name: "Jam",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v38",
        sku: "JAM-JAM",
        name: "jam",
        size: "One Size",
        color: "jam",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 50000,
        barcode: "",
      },
    ],
  },
  {
    id: "p17",
    sku: "JEDAI",
    name: "Jedai",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v39",
        sku: "JEDAI-JEDAI",
        name: "jedai",
        size: "One Size",
        color: "jedai",
        colorCode: "#000000",
        sellingPrice: 25000,
        costPrice: 10000,
        barcode: "",
      },
    ],
  },
  {
    id: "p18",
    sku: "KAIN",
    name: "Kain",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v40",
        sku: "KAIN-KAIN-VISCOSE",
        name: "Kain Viscose",
        size: "One Size",
        color: "Kain Viscose",
        colorCode: "#000000",
        sellingPrice: 165000,
        costPrice: 110000,
        barcode: "",
      },
      {
        id: "v41",
        sku: "KAIN-KAIN-PARIS",
        name: "Kain Paris",
        size: "One Size",
        color: "Kain Paris",
        colorCode: "#000000",
        sellingPrice: 135000,
        costPrice: 90000,
        barcode: "",
      },
      {
        id: "v42",
        sku: "KAIN-KAIN-LILIT",
        name: "Kain Lilit",
        size: "One Size",
        color: "Kain Lilit",
        colorCode: "#000000",
        sellingPrice: 135000,
        costPrice: 85000,
        barcode: "",
      },
      {
        id: "v43",
        sku: "KAIN-KAIN-KATUN",
        name: "Kain Katun",
        size: "One Size",
        color: "Kain Katun",
        colorCode: "#000000",
        sellingPrice: 120000,
        costPrice: 60000,
        barcode: "",
      },
      {
        id: "v44",
        sku: "KAIN-KAIN-ENCIM",
        name: "Kain Encim",
        size: "One Size",
        color: "Kain Encim",
        colorCode: "#000000",
        sellingPrice: 400000,
        costPrice: 200000,
        barcode: "",
      },
      {
        id: "v45",
        sku: "KAIN-JARIK-LAWASAN",
        name: "Jarik Lawasan",
        size: "One Size",
        color: "Jarik Lawasan",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 100000,
        barcode: "",
      },
      {
        id: "v46",
        sku: "KAIN-KAIN-MU",
        name: "kain MU",
        size: "One Size",
        color: "kain MU",
        colorCode: "#000000",
        sellingPrice: 250000,
        costPrice: 125000,
        barcode: "",
      },
      {
        id: "v47",
        sku: "KAIN-KAIN-BATIK",
        name: "kain batik",
        size: "One Size",
        color: "kain batik",
        colorCode: "#000000",
        sellingPrice: 100000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v48",
        sku: "KAIN-KAIN",
        name: "kain",
        size: "One Size",
        color: "kain",
        colorCode: "#000000",
        sellingPrice: 80000,
        costPrice: 40000,
        barcode: "",
      },
      {
        id: "v49",
        sku: "KAIN-KAIN-PRINT",
        name: "kain print",
        size: "One Size",
        color: "kain print",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 100000,
        barcode: "",
      },
      {
        id: "v50",
        sku: "KAIN-KAIN-SUTRA",
        name: "kain sutra",
        size: "One Size",
        color: "kain sutra",
        colorCode: "#000000",
        sellingPrice: 450000,
        costPrice: 200000,
        barcode: "",
      },
      {
        id: "v51",
        sku: "KAIN-KAIN-MSU",
        name: "kain msu",
        size: "One Size",
        color: "kain msu",
        colorCode: "#000000",
        sellingPrice: 165000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v52",
        sku: "KAIN-KAIN-COKLAT",
        name: "kain coklat",
        size: "One Size",
        color: "kain coklat",
        colorCode: "#000000",
        sellingPrice: 400000,
        costPrice: 200000,
        barcode: "",
      },
      {
        id: "v53",
        sku: "KAIN-KAIN-HITAM",
        name: "kain hitam",
        size: "One Size",
        color: "kain hitam",
        colorCode: "#000000",
        sellingPrice: 250000,
        costPrice: 100000,
        barcode: "",
      },
    ],
  },
  {
    id: "p19",
    sku: "KALUNG",
    name: "Kalung",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v54",
        sku: "KALUNG-KALUNG",
        name: "kalung",
        size: "One Size",
        color: "kalung",
        colorCode: "#000000",
        sellingPrice: 100000,
        costPrice: 50000,
        barcode: "",
      },
    ],
  },
  {
    id: "p20",
    sku: "KAMISOL",
    name: "Kamisol",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v55",
        sku: "KAMISOL-KAMISOL",
        name: "Kamisol",
        size: "One Size",
        color: "Kamisol",
        colorCode: "#000000",
        sellingPrice: 75000,
        costPrice: 25000,
        barcode: "",
      },
    ],
  },
  {
    id: "p21",
    sku: "KEBAYA",
    name: "Kebaya",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v56",
        sku: "KEBAYA-KEBAYA",
        name: "Kebaya",
        size: "One Size",
        color: "Kebaya",
        colorCode: "#000000",
        sellingPrice: 125000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v57",
        sku: "KEBAYA-KEBAYA-ENCIM",
        name: "Kebaya Encim",
        size: "One Size",
        color: "Kebaya Encim",
        colorCode: "#000000",
        sellingPrice: 700000,
        costPrice: 350000,
        barcode: "",
      },
      {
        id: "v58",
        sku: "KEBAYA-KEBAYA-LAWASAN",
        name: "Kebaya Lawasan",
        size: "One Size",
        color: "Kebaya Lawasan",
        colorCode: "#000000",
        sellingPrice: 130000,
        costPrice: 75000,
        barcode: "",
      },
      {
        id: "v59",
        sku: "KEBAYA-KEBAYA-B",
        name: "Kebaya B",
        size: "One Size",
        color: "Kebaya B",
        colorCode: "#000000",
        sellingPrice: 130000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v60",
        sku: "KEBAYA-KEBAYA-P",
        name: "Kebaya P",
        size: "One Size",
        color: "Kebaya P",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 60000,
        barcode: "",
      },
      {
        id: "v61",
        sku: "KEBAYA-KEBAYA-KUTANG",
        name: "Kebaya Kutang",
        size: "One Size",
        color: "Kebaya Kutang",
        colorCode: "#000000",
        sellingPrice: 90000,
        costPrice: 40000,
        barcode: "",
      },
      {
        id: "v62",
        sku: "KEBAYA-KEBAYA-C",
        name: "Kebaya C",
        size: "One Size",
        color: "Kebaya C",
        colorCode: "#000000",
        sellingPrice: 135000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v63",
        sku: "KEBAYA-KEBAYA-D",
        name: "Kebaya D",
        size: "One Size",
        color: "Kebaya D",
        colorCode: "#000000",
        sellingPrice: 140000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v64",
        sku: "KEBAYA-KEBAYA-A",
        name: "Kebaya A",
        size: "One Size",
        color: "Kebaya A",
        colorCode: "#000000",
        sellingPrice: 120000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v65",
        sku: "KEBAYA-KEBAYA-K",
        name: "Kebaya K",
        size: "One Size",
        color: "Kebaya K",
        colorCode: "#000000",
        sellingPrice: 115000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v66",
        sku: "KEBAYA-KEBAYA-S",
        name: "Kebaya S",
        size: "One Size",
        color: "Kebaya S",
        colorCode: "#000000",
        sellingPrice: 110000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v67",
        sku: "KEBAYA-KEBAYA-BALI",
        name: "Kebaya Bali",
        size: "One Size",
        color: "Kebaya Bali",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 90000,
        barcode: "",
      },
      {
        id: "v68",
        sku: "KEBAYA-KEBAYA-E",
        name: "Kebaya E",
        size: "One Size",
        color: "Kebaya E",
        colorCode: "#000000",
        sellingPrice: 145000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v69",
        sku: "KEBAYA-KEBAYA-O",
        name: "kebaya o",
        size: "One Size",
        color: "kebaya o",
        colorCode: "#000000",
        sellingPrice: 100000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v70",
        sku: "KEBAYA-SEWA-KEBAYA",
        name: "sewa kebaya",
        size: "One Size",
        color: "sewa kebaya",
        colorCode: "#000000",
        sellingPrice: 35000,
        costPrice: 5000,
        barcode: "",
      },
      {
        id: "v71",
        sku: "KEBAYA-KEBAYA-BUNGA",
        name: "kebaya bunga",
        size: "One Size",
        color: "kebaya bunga",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 80000,
        barcode: "",
      },
      {
        id: "v72",
        sku: "KEBAYA-KEBAYA-JANGGAN",
        name: "kebaya janggan",
        size: "One Size",
        color: "kebaya janggan",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 95000,
        barcode: "",
      },
      {
        id: "v73",
        sku: "KEBAYA-KEBAYA-BUNGA-S",
        name: "kebaya bunga s",
        size: "One Size",
        color: "kebaya bunga s",
        colorCode: "#000000",
        sellingPrice: 169000,
        costPrice: 72000,
        barcode: "",
      },
      {
        id: "v74",
        sku: "KEBAYA-KEBAYA-BATIK",
        name: "kebaya batik",
        size: "One Size",
        color: "kebaya batik",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 100000,
        barcode: "",
      },
      {
        id: "v75",
        sku: "KEBAYA-KEBAYA-ILORA",
        name: "kebaya ilora",
        size: "One Size",
        color: "kebaya ilora",
        colorCode: "#000000",
        sellingPrice: 550000,
        costPrice: 250000,
        barcode: "",
      },
      {
        id: "v76",
        sku: "KEBAYA-KEBAYA-FORMAL",
        name: "kebaya formal",
        size: "One Size",
        color: "kebaya formal",
        colorCode: "#000000",
        sellingPrice: 551000,
        costPrice: 250000,
        barcode: "",
      },
      {
        id: "v77",
        sku: "KEBAYA-KEBAYA-ILLORA",
        name: "kebaya illora",
        size: "One Size",
        color: "kebaya illora",
        colorCode: "#000000",
        sellingPrice: 550000,
        costPrice: 250000,
        barcode: "",
      },
      {
        id: "v78",
        sku: "KEBAYA-KEBAYA-ANAK",
        name: "kebaya anak",
        size: "One Size",
        color: "kebaya anak",
        colorCode: "#000000",
        sellingPrice: 175000,
        costPrice: 60000,
        barcode: "",
      },
      {
        id: "v79",
        sku: "KEBAYA-KEBAYA-LIORA",
        name: "kebaya liora",
        size: "One Size",
        color: "kebaya liora",
        colorCode: "#000000",
        sellingPrice: 550000,
        costPrice: 250000,
        barcode: "",
      },
    ],
  },
  {
    id: "p22",
    sku: "KEMBEN",
    name: "Kemben",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v80",
        sku: "KEMBEN-KEMBEN",
        name: "kemben",
        size: "One Size",
        color: "kemben",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
    ],
  },
  {
    id: "p23",
    sku: "KEMEJA-COWOK",
    name: "Kemeja Cowok",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v81",
        sku: "KEMEJA-COWOK-KEMEJA-COWOK",
        name: "kemeja cowok",
        size: "One Size",
        color: "kemeja cowok",
        colorCode: "#000000",
        sellingPrice: 160000,
        costPrice: 50000,
        barcode: "",
      },
    ],
  },
  {
    id: "p24",
    sku: "KIM",
    name: "Kim",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v82",
        sku: "KIM-KIM",
        name: "Kim",
        size: "One Size",
        color: "Kim",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 100000,
        barcode: "",
      },
    ],
  },
  {
    id: "p25",
    sku: "KONDE",
    name: "Konde",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v83",
        sku: "KONDE-KONDE",
        name: "konde",
        size: "One Size",
        color: "konde",
        colorCode: "#000000",
        sellingPrice: 75000,
        costPrice: 35000,
        barcode: "",
      },
    ],
  },
  {
    id: "p26",
    sku: "KUTANG",
    name: "Kutang",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v84",
        sku: "KUTANG-KUTANG",
        name: "Kutang",
        size: "One Size",
        color: "Kutang",
        colorCode: "#000000",
        sellingPrice: 70000,
        costPrice: 45000,
        barcode: "",
      },
      {
        id: "v85",
        sku: "KUTANG-KUTANG-BATIK",
        name: "Kutang Batik",
        size: "One Size",
        color: "Kutang Batik",
        colorCode: "#000000",
        sellingPrice: 70000,
        costPrice: 40000,
        barcode: "",
      },
      {
        id: "v86",
        sku: "KUTANG-KUTANG-SUROSO",
        name: "Kutang Suroso",
        size: "One Size",
        color: "Kutang Suroso",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 15000,
        barcode: "",
      },
    ],
  },
  {
    id: "p27",
    sku: "LONGTORSO",
    name: "Longtorso",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v87",
        sku: "LONGTORSO-LONGTORSO",
        name: "longtorso",
        size: "One Size",
        color: "longtorso",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 25000,
        barcode: "",
      },
    ],
  },
  {
    id: "p28",
    sku: "MAGNET",
    name: "Magnet",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v88",
        sku: "MAGNET-MAGNET",
        name: "magnet",
        size: "One Size",
        color: "magnet",
        colorCode: "#000000",
        sellingPrice: 15000,
        costPrice: 5000,
        barcode: "",
      },
    ],
  },
  {
    id: "p29",
    sku: "MANIK",
    name: "Manik",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v89",
        sku: "MANIK-MANIK",
        name: "Manik",
        size: "One Size",
        color: "Manik",
        colorCode: "#000000",
        sellingPrice: 15000,
        costPrice: 5000,
        barcode: "",
      },
      {
        id: "v90",
        sku: "MANIK-MANIK-GIOK",
        name: "manik giok",
        size: "One Size",
        color: "manik giok",
        colorCode: "#000000",
        sellingPrice: 30000,
        costPrice: 15000,
        barcode: "",
      },
    ],
  },
  {
    id: "p30",
    sku: "MANSET",
    name: "Manset",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v91",
        sku: "MANSET-MANSET",
        name: "manset",
        size: "One Size",
        color: "manset",
        colorCode: "#000000",
        sellingPrice: 60000,
        costPrice: 30000,
        barcode: "",
      },
    ],
  },
  {
    id: "p31",
    sku: "OBI",
    name: "Obi",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v92",
        sku: "OBI-OBI-VISCOSE",
        name: "Obi Viscose",
        size: "One Size",
        color: "Obi Viscose",
        colorCode: "#000000",
        sellingPrice: 60000,
        costPrice: 20000,
        barcode: "",
      },
      {
        id: "v93",
        sku: "OBI-OBI-BIASA",
        name: "Obi Biasa",
        size: "One Size",
        color: "Obi Biasa",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 30000,
        barcode: "",
      },
      {
        id: "v94",
        sku: "OBI-OBI-KERAS",
        name: "Obi Keras",
        size: "One Size",
        color: "Obi Keras",
        colorCode: "#000000",
        sellingPrice: 80000,
        costPrice: 40000,
        barcode: "",
      },
    ],
  },
  {
    id: "p32",
    sku: "OUTER",
    name: "Outer",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v95",
        sku: "OUTER-OUTER",
        name: "outer",
        size: "One Size",
        color: "outer",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 125000,
        barcode: "",
      },
    ],
  },
  {
    id: "p33",
    sku: "POST-CARD",
    name: "Post Card",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v96",
        sku: "POST-CARD-POST-CARD",
        name: "Post Card",
        size: "One Size",
        color: "Post Card",
        colorCode: "#000000",
        sellingPrice: 5000,
        costPrice: 2000,
        barcode: "",
      },
    ],
  },
  {
    id: "p34",
    sku: "RING",
    name: "Ring",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v97",
        sku: "RING-RING",
        name: "ring",
        size: "One Size",
        color: "ring",
        colorCode: "#000000",
        sellingPrice: 20000,
        costPrice: 0,
        barcode: "",
      },
    ],
  },
  {
    id: "p35",
    sku: "ROK",
    name: "Rok",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v98",
        sku: "ROK-ROK",
        name: "Rok",
        size: "One Size",
        color: "Rok",
        colorCode: "#000000",
        sellingPrice: 85000,
        costPrice: 30000,
        barcode: "",
      },
      {
        id: "v99",
        sku: "ROK-ROK-SELENDANG",
        name: "rok selendang",
        size: "One Size",
        color: "rok selendang",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
      {
        id: "v100",
        sku: "ROK-ROK-LILIT",
        name: "rok lilit",
        size: "One Size",
        color: "rok lilit",
        colorCode: "#000000",
        sellingPrice: 135000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v101",
        sku: "ROK-ROK-SUTRA",
        name: "rok sutra",
        size: "One Size",
        color: "rok sutra",
        colorCode: "#000000",
        sellingPrice: 200000,
        costPrice: 100000,
        barcode: "",
      },
    ],
  },
  {
    id: "p36",
    sku: "SARUNG-BANTAL",
    name: "Sarung Bantal",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v102",
        sku: "SARUNG-BANTAL-SARUNG-BANTAL",
        name: "sarung bantal",
        size: "One Size",
        color: "sarung bantal",
        colorCode: "#000000",
        sellingPrice: 65000,
        costPrice: 30000,
        barcode: "",
      },
    ],
  },
  {
    id: "p37",
    sku: "SCRUNCHIE",
    name: "Scrunchie",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v103",
        sku: "SCRUNCHIE-SCRUNCHIE",
        name: "scrunchie",
        size: "One Size",
        color: "scrunchie",
        colorCode: "#000000",
        sellingPrice: 15000,
        costPrice: 5000,
        barcode: "",
      },
    ],
  },
  {
    id: "p38",
    sku: "SCRUNCIE",
    name: "Scruncie",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v104",
        sku: "SCRUNCIE-SCRUNCIE",
        name: "Scruncie",
        size: "One Size",
        color: "Scruncie",
        colorCode: "#000000",
        sellingPrice: 10000,
        costPrice: 5000,
        barcode: "",
      },
    ],
  },
  {
    id: "p39",
    sku: "SELENDANG",
    name: "Selendang",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v105",
        sku: "SELENDANG-SELENDANG",
        name: "Selendang",
        size: "One Size",
        color: "Selendang",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 15000,
        barcode: "",
      },
      {
        id: "v106",
        sku: "SELENDANG-SELENDANG-P",
        name: "Selendang P",
        size: "One Size",
        color: "Selendang P",
        colorCode: "#000000",
        sellingPrice: 40000,
        costPrice: 10000,
        barcode: "",
      },
      {
        id: "v107",
        sku: "SELENDANG-SELENDANG-SUTRA",
        name: "selendang sutra",
        size: "One Size",
        color: "selendang sutra",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
    ],
  },
  {
    id: "p40",
    sku: "SEWA",
    name: "Sewa",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v108",
        sku: "SEWA-SEWA-BAWAHAN",
        name: "sewa bawahan",
        size: "One Size",
        color: "sewa bawahan",
        colorCode: "#000000",
        sellingPrice: 35000,
        costPrice: 5000,
        barcode: "",
      },
      {
        id: "v109",
        sku: "SEWA-SEWA-OBI",
        name: "sewa obi",
        size: "One Size",
        color: "sewa obi",
        colorCode: "#000000",
        sellingPrice: 15000,
        costPrice: 5000,
        barcode: "",
      },
      {
        id: "v110",
        sku: "SEWA-SEWA-SET",
        name: "sewa set",
        size: "One Size",
        color: "sewa set",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 10000,
        barcode: "",
      },
    ],
  },
  {
    id: "p41",
    sku: "TAM-NEWMAN",
    name: "Tam Newman",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v111",
        sku: "TAM-NEWMAN-TAM-NEWMAN",
        name: "tam newman",
        size: "One Size",
        color: "tam newman",
        colorCode: "#000000",
        sellingPrice: 1000000,
        costPrice: 500000,
        barcode: "",
      },
    ],
  },
  {
    id: "p42",
    sku: "TANKTOP",
    name: "Tanktop",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v112",
        sku: "TANKTOP-TANKTOP",
        name: "tanktop",
        size: "One Size",
        color: "tanktop",
        colorCode: "#000000",
        sellingPrice: 40000,
        costPrice: 15000,
        barcode: "",
      },
    ],
  },
  {
    id: "p43",
    sku: "TAPLAK",
    name: "Taplak",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v113",
        sku: "TAPLAK-TAPLAK-KECIL",
        name: "taplak kecil",
        size: "One Size",
        color: "taplak kecil",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 25000,
        barcode: "",
      },
      {
        id: "v114",
        sku: "TAPLAK-TAPLAK-BESAR",
        name: "taplak besar",
        size: "One Size",
        color: "taplak besar",
        colorCode: "#000000",
        sellingPrice: 125000,
        costPrice: 50000,
        barcode: "",
      },
      {
        id: "v115",
        sku: "TAPLAK-TAPLAK",
        name: "taplak",
        size: "One Size",
        color: "taplak",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
      {
        id: "v116",
        sku: "TAPLAK-TAPLAK-BUNGA",
        name: "taplak bunga",
        size: "One Size",
        color: "taplak bunga",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 20000,
        barcode: "",
      },
      {
        id: "v117",
        sku: "TAPLAK-TAPLAK-BATIK",
        name: "taplak batik",
        size: "One Size",
        color: "taplak batik",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 75000,
        barcode: "",
      },
    ],
  },
  {
    id: "p44",
    sku: "TAS",
    name: "Tas",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v118",
        sku: "TAS-TAS-SEGITIGA",
        name: "Tas Segitiga",
        size: "One Size",
        color: "Tas Segitiga",
        colorCode: "#000000",
        sellingPrice: 50000,
        costPrice: 25000,
        barcode: "",
      },
      {
        id: "v119",
        sku: "TAS-TAS",
        name: "tas",
        size: "One Size",
        color: "tas",
        colorCode: "#000000",
        sellingPrice: 150000,
        costPrice: 100000,
        barcode: "",
      },
      {
        id: "v120",
        sku: "TAS-TAS-TEPUNG",
        name: "tas tepung",
        size: "One Size",
        color: "tas tepung",
        colorCode: "#000000",
        sellingPrice: 20000,
        costPrice: 10000,
        barcode: "",
      },
      {
        id: "v121",
        sku: "TAS-TAS-KOIN",
        name: "tas koin",
        size: "One Size",
        color: "tas koin",
        colorCode: "#000000",
        sellingPrice: 125000,
        costPrice: 50000,
        barcode: "",
      },
    ],
  },
  {
    id: "p45",
    sku: "TULIP",
    name: "Tulip",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v122",
        sku: "TULIP-TULIP",
        name: "Tulip",
        size: "One Size",
        color: "Tulip",
        colorCode: "#000000",
        sellingPrice: 40000,
        costPrice: 25000,
        barcode: "",
      },
    ],
  },
  {
    id: "p46",
    sku: "TUNIK",
    name: "Tunik",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v123",
        sku: "TUNIK-TUNIK",
        name: "tunik",
        size: "One Size",
        color: "tunik",
        colorCode: "#000000",
        sellingPrice: 450000,
        costPrice: 200000,
        barcode: "",
      },
    ],
  },
  {
    id: "p47",
    sku: "VEST",
    name: "Vest",
    description: "",
    categoryId: "",
    images: [],
    tags: [],
    active: true,
    stock: 10,
    fabric: "",
    care: "",
    variants: [
      {
        id: "v124",
        sku: "VEST-VEST",
        name: "Vest",
        size: "One Size",
        color: "Vest",
        colorCode: "#000000",
        sellingPrice: 100000,
        costPrice: 50000,
        barcode: "",
      },
    ],
  },
];

export const customers: Customer[] = [
  { id: "c1", name: "Siti", phone: "0812-3456-7890", totalPurchases: 1250000, visitCount: 3 },
  { id: "c2", name: "Dewi", phone: "0821-9988-7766", totalPurchases: 870000, visitCount: 2 },
];

export const transactions: Transaction[] = [
  {
    id: "dummy-tx-TRX20260903001",
    number: "TRX20260903001",
    cashier: "Dewi",
    customerName: "Bu Yanti",
    status: "paid",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 120000,
    tax: 0,
    discount: 0,
    total: 120000,
    amountPaid: 120000,
    change: 0,
    createdAt: "2026-09-03T09:40:00",
    items: [
      {
        productId: "p18",
        variantId: "v43",
        name: "Kain Katun",
        sku: "KAIN-KAIN-KATUN",
        size: "One Size",
        color: "Kain Katun",
        quantity: 1,
        unitPrice: 120000,
        costPrice: 60000,
        discount: 0,
        total: 120000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903002",
    number: "TRX20260903002",
    cashier: "Oma",
    customerName: "Bu Yanti",
    status: "paid",
    paymentMethod: "shopee",
    paymentStatus: "paid",
    subtotal: 150000,
    tax: 0,
    discount: 10000,
    total: 140000,
    amountPaid: 140000,
    change: 0,
    createdAt: "2026-09-03T10:02:00",
    items: [
      {
        productId: "p14",
        variantId: "v34",
        name: "Gelang",
        sku: "GELANG-GELANG",
        size: "One Size",
        color: "Gelang",
        quantity: 1,
        unitPrice: 150000,
        costPrice: 75000,
        discount: 0,
        total: 150000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903003",
    number: "TRX20260903003",
    cashier: "Siti",
    status: "paid",
    paymentMethod: "cash",
    paymentStatus: "paid",
    subtotal: 50000,
    tax: 0,
    discount: 0,
    total: 50000,
    amountPaid: 100000,
    change: 50000,
    createdAt: "2026-09-03T11:37:00",
    items: [
      {
        productId: "p1",
        variantId: "v2",
        name: "Anting S",
        sku: "ANTING-ANTING-S",
        size: "One Size",
        color: "Anting S",
        quantity: 1,
        unitPrice: 50000,
        costPrice: 25000,
        discount: 0,
        total: 50000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903004",
    number: "TRX20260903004",
    cashier: "Dewi",
    status: "paid",
    paymentMethod: "shopee",
    paymentStatus: "paid",
    subtotal: 160000,
    tax: 0,
    discount: 0,
    total: 160000,
    amountPaid: 160000,
    change: 0,
    createdAt: "2026-09-03T12:05:00",
    items: [
      {
        productId: "p23",
        variantId: "v81",
        name: "kemeja cowok",
        sku: "KEMEJA-COWOK-KEMEJA-COWOK",
        size: "One Size",
        color: "kemeja cowok",
        quantity: 1,
        unitPrice: 160000,
        costPrice: 50000,
        discount: 0,
        total: 160000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903005",
    number: "TRX20260903005",
    cashier: "Dewi",
    customerName: "Siti",
    status: "paid",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 100000,
    tax: 0,
    discount: 0,
    total: 100000,
    amountPaid: 100000,
    change: 0,
    createdAt: "2026-09-03T13:24:00",
    items: [
      {
        productId: "p19",
        variantId: "v54",
        name: "kalung",
        sku: "KALUNG-KALUNG",
        size: "One Size",
        color: "kalung",
        quantity: 1,
        unitPrice: 100000,
        costPrice: 50000,
        discount: 0,
        total: 100000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903006",
    number: "TRX20260903006",
    cashier: "Dewi",
    customerName: "Dewi",
    status: "paid",
    paymentMethod: "shopee",
    paymentStatus: "paid",
    subtotal: 100000,
    tax: 0,
    discount: 0,
    total: 100000,
    amountPaid: 100000,
    change: 0,
    createdAt: "2026-09-03T14:49:00",
    items: [
      {
        productId: "p6",
        variantId: "v18",
        name: "bros",
        sku: "BROS-BROS",
        size: "One Size",
        color: "bros",
        quantity: 2,
        unitPrice: 50000,
        costPrice: 8000,
        discount: 0,
        total: 100000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903007",
    number: "TRX20260903007",
    cashier: "Dewi",
    customerName: "Siti",
    status: "paid",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 100000,
    tax: 0,
    discount: 0,
    total: 100000,
    amountPaid: 100000,
    change: 0,
    createdAt: "2026-09-03T15:10:00",
    items: [
      {
        productId: "p14",
        variantId: "v36",
        name: "gelang batu",
        sku: "GELANG-GELANG-BATU",
        size: "One Size",
        color: "gelang batu",
        quantity: 1,
        unitPrice: 100000,
        costPrice: 50000,
        discount: 0,
        total: 100000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903008",
    number: "TRX20260903008",
    cashier: "Oma",
    status: "paid",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 1015000,
    tax: 0,
    discount: 0,
    total: 1015000,
    amountPaid: 1015000,
    change: 0,
    createdAt: "2026-09-03T16:34:00",
    items: [
      {
        productId: "p11",
        variantId: "v31",
        name: "dompet",
        sku: "DOMPET-DOMPET",
        size: "One Size",
        color: "dompet",
        quantity: 1,
        unitPrice: 15000,
        costPrice: 6000,
        discount: 0,
        total: 15000,
      },
      {
        productId: "p41",
        variantId: "v111",
        name: "tam newman",
        sku: "TAM-NEWMAN-TAM-NEWMAN",
        size: "One Size",
        color: "tam newman",
        quantity: 1,
        unitPrice: 1000000,
        costPrice: 500000,
        discount: 0,
        total: 1000000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260903009",
    number: "TRX20260903009",
    cashier: "Siti",
    status: "cancelled",
    paymentMethod: "cash",
    paymentStatus: "paid",
    subtotal: 75000,
    tax: 0,
    discount: 0,
    total: 75000,
    amountPaid: 75000,
    change: 0,
    createdAt: "2026-09-03T17:05:00",
    items: [
      {
        productId: "p1",
        variantId: "v3",
        name: "Anting M",
        sku: "ANTING-ANTING-M",
        size: "One Size",
        color: "Anting M",
        quantity: 1,
        unitPrice: 75000,
        costPrice: 50000,
        discount: 0,
        total: 75000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260902010",
    number: "TRX20260902010",
    cashier: "Oma",
    customerName: "Bu Yanti",
    status: "paid",
    paymentMethod: "transfer",
    paymentStatus: "paid",
    subtotal: 60000,
    tax: 0,
    discount: 0,
    total: 60000,
    amountPaid: 60000,
    change: 0,
    createdAt: "2026-09-02T09:20:00",
    items: [
      {
        productId: "p5",
        variantId: "v17",
        name: "BC",
        sku: "BC-BC",
        size: "One Size",
        color: "BC",
        quantity: 3,
        unitPrice: 20000,
        costPrice: 8100,
        discount: 0,
        total: 60000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260902011",
    number: "TRX20260902011",
    cashier: "Siti",
    customerName: "Siti",
    status: "paid",
    paymentMethod: "shopee",
    paymentStatus: "paid",
    subtotal: 470000,
    tax: 0,
    discount: 0,
    total: 470000,
    amountPaid: 470000,
    change: 0,
    createdAt: "2026-09-02T10:25:00",
    items: [
      {
        productId: "p42",
        variantId: "v112",
        name: "tanktop",
        sku: "TANKTOP-TANKTOP",
        size: "One Size",
        color: "tanktop",
        quantity: 1,
        unitPrice: 40000,
        costPrice: 15000,
        discount: 0,
        total: 40000,
      },
      {
        productId: "p9",
        variantId: "v27",
        name: "Curated",
        sku: "CURATED-CURATED",
        size: "One Size",
        color: "Curated",
        quantity: 2,
        unitPrice: 80000,
        costPrice: 40000,
        discount: 0,
        total: 160000,
      },
      {
        productId: "p35",
        variantId: "v100",
        name: "rok lilit",
        sku: "ROK-ROK-LILIT",
        size: "One Size",
        color: "rok lilit",
        quantity: 2,
        unitPrice: 135000,
        costPrice: 50000,
        discount: 0,
        total: 270000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260902012",
    number: "TRX20260902012",
    cashier: "Siti",
    customerName: "Bu Yanti",
    status: "paid",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 200000,
    tax: 0,
    discount: 0,
    total: 200000,
    amountPaid: 200000,
    change: 0,
    createdAt: "2026-09-02T11:08:00",
    items: [
      {
        productId: "p6",
        variantId: "v18",
        name: "bros",
        sku: "BROS-BROS",
        size: "One Size",
        color: "bros",
        quantity: 2,
        unitPrice: 50000,
        costPrice: 8000,
        discount: 0,
        total: 100000,
      },
      {
        productId: "p10",
        variantId: "v29",
        name: "Daster",
        sku: "DASTER-DASTER",
        size: "One Size",
        color: "Daster",
        quantity: 2,
        unitPrice: 50000,
        costPrice: 37500,
        discount: 0,
        total: 100000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260902013",
    number: "TRX20260902013",
    cashier: "Siti",
    customerName: "Siti",
    status: "paid",
    paymentMethod: "transfer",
    paymentStatus: "paid",
    subtotal: 480000,
    tax: 0,
    discount: 0,
    total: 480000,
    amountPaid: 480000,
    change: 0,
    createdAt: "2026-09-02T12:38:00",
    items: [
      {
        productId: "p34",
        variantId: "v97",
        name: "ring",
        sku: "RING-RING",
        size: "One Size",
        color: "ring",
        quantity: 3,
        unitPrice: 20000,
        costPrice: 0,
        discount: 0,
        total: 60000,
      },
      {
        productId: "p1",
        variantId: "v1",
        name: "Anting",
        sku: "ANTING-ANTING",
        size: "One Size",
        color: "Anting",
        quantity: 1,
        unitPrice: 150000,
        costPrice: 75000,
        discount: 0,
        total: 150000,
      },
      {
        productId: "p35",
        variantId: "v100",
        name: "rok lilit",
        sku: "ROK-ROK-LILIT",
        size: "One Size",
        color: "rok lilit",
        quantity: 2,
        unitPrice: 135000,
        costPrice: 50000,
        discount: 0,
        total: 270000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260902014",
    number: "TRX20260902014",
    cashier: "Dewi",
    customerName: "Dewi",
    status: "paid",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 300000,
    tax: 0,
    discount: 0,
    total: 300000,
    amountPaid: 300000,
    change: 0,
    createdAt: "2026-09-02T13:29:00",
    items: [
      {
        productId: "p47",
        variantId: "v124",
        name: "Vest",
        sku: "VEST-VEST",
        size: "One Size",
        color: "Vest",
        quantity: 3,
        unitPrice: 100000,
        costPrice: 50000,
        discount: 0,
        total: 300000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260902015",
    number: "TRX20260902015",
    cashier: "Siti",
    customerName: "Dewi",
    status: "refunded",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 25000,
    tax: 0,
    discount: 0,
    total: 25000,
    amountPaid: 25000,
    change: 0,
    createdAt: "2026-09-02T14:40:00",
    items: [
      {
        productId: "p13",
        variantId: "v33",
        name: "ganci",
        sku: "GANCI-GANCI",
        size: "One Size",
        color: "ganci",
        quantity: 1,
        unitPrice: 10000,
        costPrice: 5000,
        discount: 0,
        total: 10000,
      },
      {
        productId: "p11",
        variantId: "v31",
        name: "dompet",
        sku: "DOMPET-DOMPET",
        size: "One Size",
        color: "dompet",
        quantity: 1,
        unitPrice: 15000,
        costPrice: 6000,
        discount: 0,
        total: 15000,
      },
    ],
  },
  {
    id: "dummy-tx-TRX20260902016",
    number: "TRX20260902016",
    cashier: "Dewi",
    customerName: "Siti",
    status: "paid",
    paymentMethod: "qris",
    paymentStatus: "paid",
    subtotal: 15000,
    tax: 0,
    discount: 0,
    total: 15000,
    amountPaid: 15000,
    change: 0,
    createdAt: "2026-09-02T15:15:00",
    items: [
      {
        productId: "p37",
        variantId: "v103",
        name: "scrunchie",
        sku: "SCRUNCHIE-SCRUNCHIE",
        size: "One Size",
        color: "scrunchie",
        quantity: 1,
        unitPrice: 15000,
        costPrice: 5000,
        discount: 0,
        total: 15000,
      },
    ],
  },
];

export const shifts: Shift[] = [];

export function formatRupiah(n: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(n);
}

export function getProductBySku(sku: string): Product | undefined {
  return products.find((p) => p.sku === sku);
}

export function categoryName(id: string): string {
  return categories.find((c) => c.id === id)?.name ?? "—";
}

// Kunci hari dalam zona waktu lokal kasir (WIB di tablet). Jangan pakai
// toISOString().slice(0,10) untuk filter harian — itu UTC dan geser 7 jam.
export function toLocalDayKey(iso: string): string {
  const d = new Date(iso);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

export function todayLocalKey(): string {
  return toLocalDayKey(new Date().toISOString());
}
